# agribot/utils/constants.py

TRANSLATIONS = {
    'en': {
        'title': 'AI-Driven Farming Assistant',
        'nav_analyze': 'Analyze',
        'nav_history': 'History',
        'nav_about': 'About',
        'welcome': 'Welcome to AgriBot',
        'upload': 'Upload Plant Image',
        'select_task': 'Select Analysis Type',
        'analyze': 'Analyze',
        'detect_disease': 'Detect Disease',
        'get_suggestions': 'Get Treatment Suggestions',
        'preventive': 'Preventive Measures',
        'general_tips': 'General Farming Tips',
        'growth': 'Growth Analysis',
        'fertilizer': 'Fertilizer Advice',
        'pest': 'Pest Identification',
        'irrigation': 'Irrigation Guidance',
        'choose_tasks': 'Select the analyses you need:',
        'choose_lang': 'Choose Language',
        'logout': 'Logout',
        'login': 'Login',
        'guest_login': 'Guest Login',
        'username': 'Username',
        'password': 'Password',
        'error_upload': 'Please upload an image and select at least one analysis type!',
        'analyzing': 'AgriBot is analyzing your plant...',
        'save_report': 'Save as TXT',
        'success_report': 'Report saved',
        'file': 'File',
        'size': 'Size',
        'dimensions': 'Dimensions',
        'support': 'Support',
        'support_text': 'For assistance, contact your local agricultural extension office.',
        'task_label': 'Analysis Type',
        'timestamp': 'Time',
        'clear_history': 'Clear History',
        'no_history': 'No conversation history yet',
        'copy': 'Copy',
        'copied': 'Copied!',
        'download': 'Download',
        'auto_login_notice': 'Auto-login enabled (You will not be logged out on page refresh).',
        'select_all': 'Select All',
        'clear_selection': 'Clear Selection'
    },
    'hi': {
        'title': 'AI-संचालित कृषि सहायक',
        'nav_analyze': 'विश्लेषण',
        'nav_history': 'इतिहास',
        'nav_about': 'के बारे में',
        'welcome': 'AgriBot में आपका स्वागत है',
        'upload': 'पौधे की तस्वीर अपलोड करें',
        'select_task': 'विश्लेषण प्रकार चुनें',
        'analyze': 'विश्लेषण करें',
        'detect_disease': 'रोग पहचान',
        'get_suggestions': 'उपचार सुझाव',
        'preventive': 'बचाव के उपाय',
        'general_tips': 'सामान्य खेती की सलाह',
        'growth': 'वृद्धि विश्लेषण',
        'fertilizer': 'उर्वरक सलाह',
        'pest': 'कीट पहचान',
        'irrigation': 'सिंचाई मार्गदर्शन',
        'choose_tasks': 'आवश्यक विश्लेषण चुनें:',
        'choose_lang': 'भाषा चुनें',
        'logout': 'लॉगआउट',
        'login': 'लॉगिन',
        'guest_login': 'अतिथि लॉगिन',
        'username': 'उपयोगकर्ता नाम',
        'password': 'पासवर्ड',
        'error_upload': 'कृपया एक छवि अपलोड करें और कम से कम एक विश्लेषण प्रकार चुनें!',
        'analyzing': 'AgriBot आपके पौधे का विश्लेषण कर रहा है...',
        'save_report': 'TXT के रूप में सेव करें',
        'success_report': 'रिपोर्ट सेव हो गई',
        'file': 'फाइल',
        'size': 'आकार',
        'dimensions': 'आयाम',
        'support': 'सहायता',
        'support_text': 'सहायता के लिए, अपने स्थानीय कृषि विस्तार कार्यालय से संपर्क करें।',
        'task_label': 'विश्लेषण प्रकार',
        'timestamp': 'समय',
        'clear_history': 'इतिहास साफ़ करें',
        'no_history': 'अभी तक कोई बातचीत का इतिहास नहीं',
        'copy': 'कॉपी करें',
        'copied': 'कॉपी हो गया!',
        'download': 'डाउनलोड',
        'auto_login_notice': 'ऑटो-लॉगिन सक्षम (पेज रीफ्रेश पर आप लॉगआउट नहीं होंगे)।',
        'select_all': 'सभी चुनें',
        'clear_selection': 'चयन साफ़ करें'
    },
    'gu': {
        'title': 'AI-સંચાલિત ખેતી સહાયક',
        'nav_analyze': 'વિશ્લેષણ',
        'nav_history': 'ઇતિહાસ',
        'nav_about': 'વિશે',
        'welcome': 'AgriBot માં તમારું સ્વાગત છે',
        'upload': 'છોડની તસવીર અપલોડ કરો',
        'select_task': 'વિશ્લેષણ પ્રકાર પસંદ કરો',
        'analyze': 'વિશ્લેષણ કરો',
        'detect_disease': 'રોગ ઓળખ',
        'get_suggestions': 'સારવાર સૂચનો',
        'preventive': 'નિવારક પગલાં',
        'general_tips': 'સામાન્ય ખેતીની સલાહ',
        'growth': 'વૃદ્ધિ વિશ્લેષણ',
        'fertilizer': 'ખાતર સલાહ',
        'pest': 'કીટક ઓળખ',
        'irrigation': 'સિંચાઈ માર્ગદર્શન',
        'choose_tasks': 'જરૂરી વિશ્લેષણ પસંદ કરો:',
        'choose_lang': 'ભાષા પસંદ કરો',
        'logout': 'લૉગઆઉટ',
        'login': 'લૉગિન',
        'guest_login': 'મહેમાન લૉગિન',
        'username': 'વપરાશકર્તા નામ',
        'password': 'પાસવર્ડ',
        'error_upload': 'કૃપા કરીને એક છબી અપલોડ કરો અને ઓછામાં ઓછો એક વિશ્લેષણ પ્રકાર પસંદ કરો!',
        'analyzing': 'AgriBot તમારા છોડનું વિશ્લેષણ કરી રહ્યું છે...',
        'save_report': 'TXT તરીકે સેવ કરો',
        'success_report': 'રિપોર્ટ સેવ થઈ ગઈ',
        'file': 'ફાઇલ',
        'size': 'કદ',
        'dimensions': 'પરિમાણો',
        'support': 'સહાય',
        'support_text': 'સહાય માટે, તમારા સ્થાનીય કૃષિ বিস্তার કાર્યલયનો સંપર્ક કરો।',
        'task_label': 'વિશ્લેષણ પ્રકાર',
        'timestamp': 'સમય',
        'clear_history': 'ઇતિહાસ સાફ કરો',
        'no_history': 'હજુ સુધી કોઈ વાર્તાલાપ ઇતિહાસ નથી',
        'copy': 'કૉપિ કરો',
        'copied': 'કૉપિ થઈ ગઈ!',
        'download': 'ડાઉનલોડ',
        'auto_login_notice': 'ઑટો-લૉગિન સક્ષમ (પેજ રીફ્રેશ પર તમે લૉગઆઉટ થશો નહીં)।',
        'select_all': 'બધું પસંદ કરો',
        'clear_selection': 'પસંદગી સાફ કરો'
    }
}

TASKS = [
    ('🦠', 'detect_disease'),
    ('💊', 'get_suggestions'),
    ('🛡', 'preventive'),
    ('📚', 'general_tips'),
    ('📈', 'growth'),
    ('🌾', 'fertilizer'),
    ('🐛', 'pest'),
    ('💧', 'irrigation')
]

USERS = {
    'user001': {'password': '1234', 'role': 'admin'},
    'farmer1': {'password': 'farm123', 'role': 'user'},
    'demo': {'password': 'demo', 'role': 'user'}
}

DATABASE = "conversations.json"
REPORTS_FOLDER = "reports"
